# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data_display(object):
    def setupUi(self, Data_display):
        Data_display.setObjectName("Data_display")
        Data_display.resize(796, 494)
        Data_display.setMouseTracking(True)
        self.groupBox = QtWidgets.QGroupBox(Data_display)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 771, 481))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(670, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 651, 451))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Data_display)
        self.pushButton.clicked.connect(self.textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(Data_display)

    def retranslateUi(self, Data_display):
        _translate = QtCore.QCoreApplication.translate
        Data_display.setWindowTitle(_translate("Data_display", "数据实时显示"))
        self.groupBox.setTitle(_translate("Data_display", "数据详情"))
        self.pushButton.setText(_translate("Data_display", "清空窗口"))
