# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_Image1(object):
    def setupUi(self, show_Image1):
        show_Image1.setObjectName("show_Image1")
        show_Image1.resize(698, 583)
        self.pushButton = QtWidgets.QPushButton(show_Image1)
        self.pushButton.setGeometry(QtCore.QRect(300, 530, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(show_Image1)
        self.label.setGeometry(QtCore.QRect(70, 20, 541, 491))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(show_Image1)
        QtCore.QMetaObject.connectSlotsByName(show_Image1)

    def retranslateUi(self, show_Image1):
        _translate = QtCore.QCoreApplication.translate
        show_Image1.setWindowTitle(_translate("show_Image1", "Form"))
        self.pushButton.setText(_translate("show_Image1", "PushButton"))
